### ISSUE TITLE
No module named 'rotate_translate'

### ISSUE THREAD

**Issue by tiptonnet** [Priyansh-15/3-D-Image-Build-from-Multiple-Images#1]
File "/home/mike/3-D-Image-Build-from-Multiple-Images/3D_Build.py", line 17, in <module>
    from rotate_translate import node
ModuleNotFoundError:

**Comment by Priyansh-15** [comment]
Hi @tiptonnet 
In the File "/home/mike/3-D-Image-Build-from-Multiple-Images/3D_Build.py", on line 17 `from rotate_translate import node` is a typo error the file name is now fixed you can find the module named "rotate_translate" which will resolve your ModuleNotFoundError .
Thanks
@Priyansh-15
